project_id = "gyafunimpnzctpfbqkgm"

[functions.finalize-contests]
verify_jwt = false

[functions.create-users]
verify_jwt = false

[functions.track-login]
verify_jwt = false

[functions.get-ip-info]
verify_jwt = false

[functions.receive-postback]
verify_jwt = false

[functions.handle-click]
verify_jwt = false

[functions.import-offers]
verify_jwt = false
